model: yolov8l.pt
data: data/yolo_polyp/data.yaml
epochs: 200
imgsz: 768
batch: 8
device: 0
workers: 8
project: runs/detect
name: polyp_v8l_768
cos_lr: true
mosaic: 0.7
close_mosaic: 10
fliplr: 0.5
degrees: 5
translate: 0.1
scale: 0.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
erasing: 0.1
